python3 main_plothighlight.py run_hydro_NH_CH_0005.json
python3 main_plothighlight.py run_hydro_NH_CH_0005_coarse.json
python3 main_plothighlight.py run_hydro_gent_CH_0005.json
python3 main_plothighlight.py run_hydro_gent_CH_0005_coarse.json
